version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports: [ "2181:2181" ]
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports: [ "9092:9092" ]
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  spark-master:
    image: bitnami/spark:latest
    ports: [ "8080:8080", "7077:7077" ]
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

  airflow:
    image: apache/airflow:2.7.1
    ports: [ "8081:8080" ]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://de_project_user:de_project_pass@postgres/de_project_db
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=de_project_user
      - POSTGRES_PASSWORD=de_project_pass
      - POSTGRES_DB=de_project_db